; This file holds every route from the API

; Route format: 
; [<authenticated> <method> <endpoint>]
; What method should be called for this endpoint
; handler = <Class>::<Method>
; body = '{"<parameter_name>":"<type>"}' (optional)

; Endpoint format:
; /<endpoint-name>/{<Some Parameter>}/...

; Endpoint Rules:
; An Endpoint should always start with '/'
; An Endpoint can have multiple parameters or no parameters
; Parameters can be anywhere in the endpoint and should always be enclosed by {}

; Endpoint naming practices:
; The endpoint should start with the name of the controller
; and then the endpoint name
; Example: /accounts/login

; Example routes:

; Example (non authenticated):
; [GET /get-routes]
; handler = GeneralController::getRoutes

; Example (Request with body):
; [POST /accounts/login]
; handler = AccountController::login
; body = '{"username":"string","password":"string"}'

; Example (Authenticated Request):
; [* GET /get-user]
; handler = UserController::login
; body = '{"username":"string","password":"string"}'

; Observações:
; Em rotas autenticadas, você sempre precisa passar o 'refresh_token'

[GET /get-routes]
handler = TestController::testMethod
body = '{"something_required": "string", "?something_optional": "string"}'

; User Related Routes
[GET /get-user/{user_id}]
handler = UserController::getUser

[POST /create-account]
handler = UserController::createAccount
body = '{"reg": "string", "email": "string", "password": "string", "username": "string", "name": "string"}'

[* POST /accounts/get-data]
handler = UserController::getAccountData

[* POST /accounts/update]
handler = UserController::updateAccountData
body = '{"?password": "string", "?username": "string", "?name": "string", "?email": "string"}'

; Rotas específicas para chefia

; Para criar o usuário da chefia, as informações de usuário padrão também são necessárias
; TODO: Adicionar as informações extras da chefia
[GET /get-chief/{user_id}]
handler = ChiefController::getChief

[POST /chief/create-account]
handler = ChiefController::createAccount
body = '{"reg": "string", "email": "string", "password": "string", "username": "string", "name": "string"}'

[* POST /accounts/chief/get-data]
handler = ChiefController::getAccountData

; TODO: Adicionar as informações extras da chefia
[* POST /accounts/chief/update]
handler = ChiefController::updateAccountData
body = '{"?password": "string", "email": "string", "?username": "string", "?name": "string"}'


; Account / Session related
[POST /accounts/login]
handler = AuthController::startSession
body = '{"reg": "string", "password": "string"}'

[POST /accounts/refresh]
handler = AuthController::refreshSession
body = '{"refresh_token": "string"}'

[POST /accounts/alive]
handler = AuthController::checkSessionStats
body = '{"refresh_token": "string"}'

[POST /accounts/quit]
handler = AuthController::quitSession
body = '{"refresh_token": "string"}'


[* POST /groups/create]
handler = GroupController::createTeam
body = '{"state": "string", "name": "string", "num": "int"}'

[* POST /groups/update]
handler = GroupController::updateTeam
body = '{"?state": "string", "?name": "string", "?num": "int"}'

[* POST /groups/delete]
handler = GroupController::deleteTeam

[* POST /groups/join/{id_team}]
handler = GroupController::joinTeam

[* POST /groups/quit]
handler = GroupController::quitTeam

[* POST /groups/update-permissions]
handler = GroupController::updateUserPermission
body = '{"target_user_id": "int", "permission_level": "int"}'

[* POST /groups/transfer-ownership]
handler = GroupController::transferOwnership
body = '{"target_user_id": "int", "password": "string", "team_name": "string"}'


[GET /groups/get-user-data/{user_id}]
handler = GroupController::getUserTeamData

[GET /groups/{id_team}]
handler = GroupController::getTeamInfo

[GET /groups/{id_team}/members]
handler = GroupController::getTeamMembers



[* POST /troups/create]
handler = TroupController::createTeam
body = '{"name": "string"}'

[* POST /troups/update]
handler = TroupController::updateTeam
body = '{"?name": "string"}'

[* POST /troups/delete]
handler = TroupController::deleteTeam

[* POST /troups/join/{id_team}]
handler = TroupController::joinTeam

[* POST /troups/quit]
handler = TroupController::quitTeam

[* POST /troups/update-permissions]
handler = TroupController::updateUserPermission
body = '{"target_user_id": "int", "permission_level": "int"}'

[* POST /troups/transfer-ownership]
handler = TroupController::transferOwnership
body = '{"target_user_id": "int", "password": "string", "team_name": "string"}'


[GET /troups/get-user-data/{user_id}]
handler = TroupController::getUserTeamData

[GET /troups/{id_team}]
handler = TroupController::getTeamInfo

[GET /troups/{id_team}/members]
handler = TroupController::getTeamMembers